-- MySQL Script generated by MySQL Workbench
-- Wed Apr  9 22:40:31 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE` (
  `idCLIENTE` INT NOT NULL AUTO_INCREMENT,
  `tipoCLIENTE` ENUM('PF', 'PJ') NOT NULL,
  PRIMARY KEY (`idCLIENTE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTEPF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTEPF` (
  `idCLIENTE` INT NOT NULL AUTO_INCREMENT,
  `Pnome` VARCHAR(10) NOT NULL,
  `Mnome` VARCHAR(3) NULL,
  `sobrenome` VARCHAR(20) NULL COMMENT 'Adiciona constraint de unicidade para (nome completo)\nunique(Nome,M, Sobrenome)',
  `cpf` VARCHAR(11) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `enderecoCLIENTEPF` VARCHAR(45) NULL,
  `CLIENTE_idCLIENTE` INT NOT NULL,
  PRIMARY KEY (`idCLIENTE`, `CLIENTE_idCLIENTE`),
  UNIQUE INDEX `identificacaoCLIENTE_UNIQUE` (`cpf` ASC) VISIBLE,
  INDEX `fk_CLIENTEPF_CLIENTE1_idx` (`CLIENTE_idCLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTEPF_CLIENTE1`
    FOREIGN KEY (`CLIENTE_idCLIENTE`)
    REFERENCES `mydb`.`CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PEDIDO` (
  `idPEDIDO` INT NOT NULL AUTO_INCREMENT,
  `status_pedido` ENUM('Em andamento', 'Processando', 'Enviado', 'Entregue') NULL DEFAULT 'Processando',
  `descricao_pedido` VARCHAR(45) NULL,
  `frete` FLOAT NULL,
  `forma_pagamento` ENUM('Cartão', 'Pix', 'Boleto') NULL,
  `status_pagamento` ENUM('Pago', 'Pendente') NULL DEFAULT 'Pendente',
  `valor_pagamento` FLOAT NULL,
  `data_pagamento` DATE NULL,
  `CLIENTE_idCLIENTE` INT NOT NULL,
  PRIMARY KEY (`idPEDIDO`, `CLIENTE_idCLIENTE`),
  INDEX `fk_PEDIDO_CLIENTE1_idx` (`CLIENTE_idCLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_idCLIENTE`)
    REFERENCES `mydb`.`CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FORNECEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FORNECEDOR` (
  `idFORNECEDOR` INT NOT NULL AUTO_INCREMENT,
  `razaosocialFORNECEDOR` VARCHAR(45) NOT NULL,
  `cnpjFORNECEDOR` VARCHAR(45) NOT NULL,
  `localFORNECEDOR` VARCHAR(45) NULL,
  PRIMARY KEY (`idFORNECEDOR`),
  UNIQUE INDEX `cnpjFORNECEDOR_UNIQUE` (`cnpjFORNECEDOR` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUTO` (
  `idPRODUTO` INT NOT NULL AUTO_INCREMENT,
  `categoriaPRODUTO` VARCHAR(45) NULL,
  `descricaoPRODUTO` VARCHAR(45) NULL,
  `valorPRODUTO` FLOAT NULL,
  PRIMARY KEY (`idPRODUTO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FORNECEDOR_has_PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FORNECEDOR_has_PRODUTO` (
  `FORNECEDOR_idFORNECEDOR` INT NOT NULL,
  `PRODUTO_idPRODUTO` INT NOT NULL,
  PRIMARY KEY (`FORNECEDOR_idFORNECEDOR`, `PRODUTO_idPRODUTO`),
  INDEX `fk_FORNECEDOR_has_PRODUTO_PRODUTO1_idx` (`PRODUTO_idPRODUTO` ASC) VISIBLE,
  INDEX `fk_FORNECEDOR_has_PRODUTO_FORNECEDOR_idx` (`FORNECEDOR_idFORNECEDOR` ASC) VISIBLE,
  CONSTRAINT `fk_FORNECEDOR_has_PRODUTO_FORNECEDOR`
    FOREIGN KEY (`FORNECEDOR_idFORNECEDOR`)
    REFERENCES `mydb`.`FORNECEDOR` (`idFORNECEDOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FORNECEDOR_has_PRODUTO_PRODUTO1`
    FOREIGN KEY (`PRODUTO_idPRODUTO`)
    REFERENCES `mydb`.`PRODUTO` (`idPRODUTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ESTOQUE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ESTOQUE` (
  `idESTOQUE` INT NOT NULL AUTO_INCREMENT,
  `localESTOQUE` VARCHAR(45) NULL,
  PRIMARY KEY (`idESTOQUE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ESTOQUE_has_PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ESTOQUE_has_PRODUTO` (
  `ESTOQUE_idESTOQUE` INT NOT NULL,
  `PRODUTO_idPRODUTO` INT NOT NULL,
  `quantidadeESTOQUE` INT NOT NULL,
  PRIMARY KEY (`ESTOQUE_idESTOQUE`, `PRODUTO_idPRODUTO`),
  INDEX `fk_ESTOQUE_has_PRODUTO_PRODUTO1_idx` (`PRODUTO_idPRODUTO` ASC) VISIBLE,
  INDEX `fk_ESTOQUE_has_PRODUTO_ESTOQUE1_idx` (`ESTOQUE_idESTOQUE` ASC) VISIBLE,
  CONSTRAINT `fk_ESTOQUE_has_PRODUTO_ESTOQUE1`
    FOREIGN KEY (`ESTOQUE_idESTOQUE`)
    REFERENCES `mydb`.`ESTOQUE` (`idESTOQUE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ESTOQUE_has_PRODUTO_PRODUTO1`
    FOREIGN KEY (`PRODUTO_idPRODUTO`)
    REFERENCES `mydb`.`PRODUTO` (`idPRODUTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PEDIDO_has_PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PEDIDO_has_PRODUTO` (
  `PEDIDO_idPEDIDO` INT NOT NULL,
  `PRODUTO_idPRODUTO` INT NOT NULL,
  `quantidadePEDIDO` INT NOT NULL,
  `statusPEDIDO` ENUM('Disponível', 'Fora de estoque') NULL DEFAULT 'Disponível',
  PRIMARY KEY (`PEDIDO_idPEDIDO`, `PRODUTO_idPRODUTO`),
  INDEX `fk_PEDIDO_has_PRODUTO_PRODUTO1_idx` (`PRODUTO_idPRODUTO` ASC) VISIBLE,
  INDEX `fk_PEDIDO_has_PRODUTO_PEDIDO1_idx` (`PEDIDO_idPEDIDO` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDO_has_PRODUTO_PEDIDO1`
    FOREIGN KEY (`PEDIDO_idPEDIDO`)
    REFERENCES `mydb`.`PEDIDO` (`idPEDIDO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_has_PRODUTO_PRODUTO1`
    FOREIGN KEY (`PRODUTO_idPRODUTO`)
    REFERENCES `mydb`.`PRODUTO` (`idPRODUTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VENDEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VENDEDOR` (
  `idVENDEDOR` INT NOT NULL AUTO_INCREMENT,
  `razaosocialVENDEDOR` VARCHAR(45) NOT NULL,
  `cnpjVENDEDOR` VARCHAR(45) NOT NULL,
  `localVENDEDOR` VARCHAR(45) NULL,
  PRIMARY KEY (`idVENDEDOR`),
  UNIQUE INDEX `cnpjTERCEIROVENDEDOR_UNIQUE` (`cnpjVENDEDOR` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VENDEDOR_has_PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VENDEDOR_has_PRODUTO` (
  `VENDEDOR_idVENDEDOR` INT NOT NULL,
  `PRODUTO_idPRODUTO` INT NOT NULL,
  `quantidade_produtoVENDEDOR` INT NULL,
  PRIMARY KEY (`VENDEDOR_idVENDEDOR`, `PRODUTO_idPRODUTO`),
  INDEX `fk_TERCEIROVENDEDOR_has_PRODUTO_PRODUTO1_idx` (`PRODUTO_idPRODUTO` ASC) VISIBLE,
  INDEX `fk_TERCEIROVENDEDOR_has_PRODUTO_TERCEIROVENDEDOR1_idx` (`VENDEDOR_idVENDEDOR` ASC) VISIBLE,
  CONSTRAINT `fk_TERCEIROVENDEDOR_has_PRODUTO_TERCEIROVENDEDOR1`
    FOREIGN KEY (`VENDEDOR_idVENDEDOR`)
    REFERENCES `mydb`.`VENDEDOR` (`idVENDEDOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TERCEIROVENDEDOR_has_PRODUTO_PRODUTO1`
    FOREIGN KEY (`PRODUTO_idPRODUTO`)
    REFERENCES `mydb`.`PRODUTO` (`idPRODUTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTEPJ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTEPJ` (
  `idCLIENTEPJ` INT NOT NULL AUTO_INCREMENT,
  `razaosocialCLIENTEPJ` VARCHAR(45) NOT NULL,
  `cnpjCLIENTEPJ` VARCHAR(45) NOT NULL,
  `enderecoCLIENTEPJ` VARCHAR(45) NULL,
  `CLIENTE_idCLIENTE` INT NOT NULL,
  PRIMARY KEY (`idCLIENTEPJ`, `CLIENTE_idCLIENTE`),
  UNIQUE INDEX `cnpjCLIENTEPJ_UNIQUE` (`cnpjCLIENTEPJ` ASC) VISIBLE,
  INDEX `fk_CLIENTEPJ_CLIENTE1_idx` (`CLIENTE_idCLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTEPJ_CLIENTE1`
    FOREIGN KEY (`CLIENTE_idCLIENTE`)
    REFERENCES `mydb`.`CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ENTREGA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ENTREGA` (
  `idENTREGA` INT NOT NULL AUTO_INCREMENT,
  `codigo_entrega` VARCHAR(45) NOT NULL,
  `status_entrega` ENUM('Processando', 'A caminho') NULL DEFAULT 'Processando',
  `PEDIDO_idPEDIDO` INT NOT NULL,
  PRIMARY KEY (`idENTREGA`, `PEDIDO_idPEDIDO`),
  UNIQUE INDEX `codigo_rastreioENTREGA_UNIQUE` (`codigo_entrega` ASC) VISIBLE,
  INDEX `fk_ENTREGA_PEDIDO1_idx` (`PEDIDO_idPEDIDO` ASC) VISIBLE,
  CONSTRAINT `fk_ENTREGA_PEDIDO1`
    FOREIGN KEY (`PEDIDO_idPEDIDO`)
    REFERENCES `mydb`.`PEDIDO` (`idPEDIDO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
