-- MySQL Script generated by MySQL Workbench
-- Thu Apr 10 16:48:35 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oficina
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema oficina
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oficina` DEFAULT CHARACTER SET utf8 ;
USE `oficina` ;

-- -----------------------------------------------------
-- Table `oficina`.`EQUIPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`EQUIPE` (
  `idEQUIPE` INT NOT NULL AUTO_INCREMENT,
  `numero_equipe` INT NOT NULL,
  PRIMARY KEY (`idEQUIPE`),
  UNIQUE INDEX `numeroEQUIPE_UNIQUE` (`numero_equipe` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`CLIENTE` (
  `idCLIENTE` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(45) NULL,
  `cpf_cliente` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idCLIENTE`),
  UNIQUE INDEX `cpfCLIENTE_UNIQUE` (`cpf_cliente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`VEICULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`VEICULO` (
  `idVEICULO` INT NOT NULL AUTO_INCREMENT,
  `nome_veiculo` VARCHAR(45) NULL,
  `placa_veiculo` VARCHAR(45) NOT NULL,
  `CLIENTE_idCLIENTE` INT NOT NULL,
  PRIMARY KEY (`idVEICULO`, `CLIENTE_idCLIENTE`),
  UNIQUE INDEX `placaVEICULO_UNIQUE` (`placa_veiculo` ASC) VISIBLE,
  INDEX `fk_VEICULO_CLIENTE1_idx` (`CLIENTE_idCLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_VEICULO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_idCLIENTE`)
    REFERENCES `oficina`.`CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`ORDEMSERVICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`ORDEMSERVICO` (
  `idORDEMSERVICO` INT NOT NULL AUTO_INCREMENT,
  `numero_ordemservico` INT NOT NULL,
  `data_inicio_ordemservico` DATE NOT NULL,
  `data_finalizacao_ordemservico` DATE NULL,
  `valor_ordemservico` DECIMAL(10,2) NULL,
  `status_ordemservico` VARCHAR(45) NULL,
  `EQUIPE_idEQUIPE` INT NOT NULL,
  `CLIENTE_idCLIENTE` INT NOT NULL,
  `VEICULO_idVEICULO` INT NOT NULL,
  PRIMARY KEY (`idORDEMSERVICO`, `EQUIPE_idEQUIPE`, `CLIENTE_idCLIENTE`, `VEICULO_idVEICULO`),
  UNIQUE INDEX `numeroSERVICO_UNIQUE` (`numero_ordemservico` ASC) VISIBLE,
  INDEX `fk_ORDEMSERVICO_EQUIPE1_idx` (`EQUIPE_idEQUIPE` ASC) VISIBLE,
  INDEX `fk_ORDEMSERVICO_CLIENTE1_idx` (`CLIENTE_idCLIENTE` ASC) VISIBLE,
  INDEX `fk_ORDEMSERVICO_VEICULO1_idx` (`VEICULO_idVEICULO` ASC) VISIBLE,
  CONSTRAINT `fk_ORDEMSERVICO_EQUIPE1`
    FOREIGN KEY (`EQUIPE_idEQUIPE`)
    REFERENCES `oficina`.`EQUIPE` (`idEQUIPE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDEMSERVICO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_idCLIENTE`)
    REFERENCES `oficina`.`CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDEMSERVICO_VEICULO1`
    FOREIGN KEY (`VEICULO_idVEICULO`)
    REFERENCES `oficina`.`VEICULO` (`idVEICULO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`SERVICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`SERVICO` (
  `idSERVICO` INT NOT NULL AUTO_INCREMENT,
  `nome_servico` VARCHAR(45) NULL,
  `valor_servico` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idSERVICO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`PECA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`PECA` (
  `idPECA` INT NOT NULL AUTO_INCREMENT,
  `valor_peca` DECIMAL(10,2) NULL,
  `nome_peca` VARCHAR(45) NULL,
  `descricao_peca` VARCHAR(45) NULL,
  PRIMARY KEY (`idPECA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`MECANICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`MECANICO` (
  `idMECANICO` INT NOT NULL AUTO_INCREMENT,
  `codigo_mecanico` VARCHAR(45) NOT NULL,
  `nome_mecanico` VARCHAR(45) NULL,
  `endereco_mecanico` VARCHAR(45) NULL,
  `especialidade_mecanico` VARCHAR(45) NULL,
  `EQUIPE_idEQUIPE` INT NOT NULL,
  PRIMARY KEY (`idMECANICO`, `EQUIPE_idEQUIPE`),
  UNIQUE INDEX `codigoMECANICO_UNIQUE` (`codigo_mecanico` ASC) VISIBLE,
  INDEX `fk_MECANICO_EQUIPE1_idx` (`EQUIPE_idEQUIPE` ASC) VISIBLE,
  CONSTRAINT `fk_MECANICO_EQUIPE1`
    FOREIGN KEY (`EQUIPE_idEQUIPE`)
    REFERENCES `oficina`.`EQUIPE` (`idEQUIPE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`ORDEMSERVICO_has_SERVICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`ORDEMSERVICO_has_SERVICO` (
  `ORDEMSERVICO_idORDEMSERVICO` INT NOT NULL,
  `SERVICO_idSERVICO` INT NOT NULL,
  `valortotal` DECIMAL(10,2) NULL,
  PRIMARY KEY (`ORDEMSERVICO_idORDEMSERVICO`, `SERVICO_idSERVICO`),
  INDEX `fk_ORDEMSERVICO_has_SERVICO_SERVICO1_idx` (`SERVICO_idSERVICO` ASC) VISIBLE,
  INDEX `fk_ORDEMSERVICO_has_SERVICO_ORDEMSERVICO_idx` (`ORDEMSERVICO_idORDEMSERVICO` ASC) VISIBLE,
  CONSTRAINT `fk_ORDEMSERVICO_has_SERVICO_ORDEMSERVICO`
    FOREIGN KEY (`ORDEMSERVICO_idORDEMSERVICO`)
    REFERENCES `oficina`.`ORDEMSERVICO` (`idORDEMSERVICO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDEMSERVICO_has_SERVICO_SERVICO1`
    FOREIGN KEY (`SERVICO_idSERVICO`)
    REFERENCES `oficina`.`SERVICO` (`idSERVICO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`SERVICO_has_PECA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`SERVICO_has_PECA` (
  `SERVICO_idSERVICO` INT NOT NULL,
  `PECA_idPECA` INT NOT NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`SERVICO_idSERVICO`, `PECA_idPECA`),
  INDEX `fk_SERVICO_has_PECA_PECA1_idx` (`PECA_idPECA` ASC) VISIBLE,
  INDEX `fk_SERVICO_has_PECA_SERVICO1_idx` (`SERVICO_idSERVICO` ASC) VISIBLE,
  CONSTRAINT `fk_SERVICO_has_PECA_SERVICO1`
    FOREIGN KEY (`SERVICO_idSERVICO`)
    REFERENCES `oficina`.`SERVICO` (`idSERVICO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SERVICO_has_PECA_PECA1`
    FOREIGN KEY (`PECA_idPECA`)
    REFERENCES `oficina`.`PECA` (`idPECA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
